use crate::provider::LightId;
use std::io::Result;
use std::path::Path;

#[derive(Clone, Debug)]
pub struct DropinConfig {
    pub provider_name: String,
    pub light_label: String,
    pub light_id: LightId,
    pub node_prefix: String,
}

impl DropinConfig {
    pub fn new(
        provider_name: String,
        light_label: String,
        light_id: LightId,
        node_prefix: String,
    ) -> Self {
        Self {
            provider_name,
            light_label,
            light_id,
            node_prefix,
        }
    }

    pub fn filename(&self) -> String {
        format!(
            "{}-{}-{}.conf",
            self.node_prefix,
            self.provider_name.to_lowercase(),
            sanitize_label(&self.light_label)
        )
    }

    pub fn generate(&self) -> String {
        let node_name = format!(
            "{}.{}.{}",
            self.node_prefix,
            self.provider_name.to_lowercase(),
            sanitize_label(&self.light_label)
        );

        format!(
            r#"# Generated by lightwire - do not edit manually
# Light: {} ({})
# Provider: {}

context.objects = [
  {{
    factory = adapter
    args = {{
      factory.name = support.null-audio-sink
      node.name = "{}"
      node.description = "{}: {}"
      media.class = Audio/Sink
      object.linger = true
      audio.position = [ FL FR ]
      monitor.channel-volumes = true
    }}
  }}
]]
"#,
            self.light_label,
            self.light_id.0,
            self.provider_name,
            node_name,
            capitalize_first(&self.provider_name),
            self.light_label
        )
    }

    pub fn write_to(&self, config_dir: &Path) -> Result<()> {
        let file_path = config_dir.join(self.filename());
        std::fs::write(file_path, self.generate())?;
        Ok(())
    }
}

fn sanitize_label(label: &str) -> String {
    label
        .to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}

fn capitalize_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
    }
}
